import 'package:flutter/material.dart';

class AppLocalizations {
  static const Map<String, Map<String, String>> _translations = {
    'en': {
      'welcome_back': 'Welcome Back',
      'login_to_account': 'Login to your account',
      'email': 'Email',
      'enter_your_email': 'Enter your email',
      'password': 'Password',
      'enter_your_password': 'Enter your password',
      'forgot_password': 'Forgot Password?',
      'login': 'Login',
      'dont_have_account': "Don't have an account?",
      'sign_up': 'Sign up',
      'create_account': 'Create Account',
      'register_to_get_started': 'Register to get started',
      'full_name': 'Full Name',
      'phone_number': 'Phone Number',
      'confirm_password': 'Confirm Password',
      'i_am_a': 'I am a...',
      'employer': 'Employer',
      'job_seeker': 'Job Seeker',
      'agree_terms': 'I agree to terms and conditions',
      'register': 'Register',
      'already_have_account': 'Already have an account?',
      'loading': 'Loading...',
      'find_perfect_job': 'Find Your Perfect Job',
      'please_fill_all_fields': 'Please fill all fields',
      'passwords_not_match': 'Passwords do not match',
      'agree_to_terms': 'Please agree to terms and conditions',
      'select_user_type': 'Please select user type',
      'logged_in_successfully': 'Logged in successfully!',
      'login_failed': 'Login failed',
      'registration_failed': 'Registration failed',
      'please_verify_email': 'Please verify your email',
    },
    'ar': {
      'welcome_back': 'مرحبا بك',
      'login_to_account': 'تسجيل الدخول إلى حسابك',
      'email': 'البريد الإلكتروني',
      'enter_your_email': 'أدخل بريدك الإلكتروني',
      'password': 'كلمة المرور',
      'enter_your_password': 'أدخل كلمة المرور',
      'forgot_password': 'هل نسيت كلمة المرور؟',
      'login': 'دخول',
      'dont_have_account': 'ليس لديك حساب؟',
      'sign_up': 'إنشاء حساب',
      'create_account': 'إنشاء حساب',
      'register_to_get_started': 'سجل للبدء',
      'full_name': 'الاسم الكامل',
      'phone_number': 'رقم الهاتف',
      'confirm_password': 'تأكيد كلمة المرور',
      'i_am_a': 'أنا...',
      'employer': 'صاحب عمل',
      'job_seeker': 'أبحث عن وظيفة',
      'agree_terms': 'أوافق على شروط الخدمة',
      'register': 'تسجيل',
      'already_have_account': 'هل لديك حساب بالفعل؟',
      'loading': 'جاري التحميل...',
      'find_perfect_job': 'ابحث عن وظيفتك المثالية',
      'please_fill_all_fields': 'الرجاء ملء جميع الحقول',
      'passwords_not_match': 'كلمات المرور غير متطابقة',
      'agree_to_terms': 'الرجاء الموافقة على شروط الخدمة',
      'select_user_type': 'الرجاء اختيار نوع المستخدم',
      'logged_in_successfully': 'تم تسجيل الدخول بنجاح!',
      'login_failed': 'فشل تسجيل الدخول',
      'registration_failed': 'فشل التسجيل',
      'please_verify_email': 'الرجاء التحقق من بريدك الإلكتروني',
    },
    'ku': {
      'welcome_back': 'بە خێربێیی',
      'login_to_account': 'چوون ژوورەوە بۆ ئەکاونتی خۆت',
      'email': 'ئیمەیل',
      'enter_your_email': 'ئیمەیلی خۆت تێبکە',
      'password': 'شیفرە',
      'enter_your_password': 'شیفرەی خۆت تێبکە',
      'forgot_password': 'شیفرە لەبیری چوو؟',
      'login': 'چوون ژوورەوە',
      'dont_have_account': 'ئەکاونتت نیە؟',
      'sign_up': 'ئەکاونت دروستبکە',
      'create_account': 'ئەکاونت دروستبکە',
      'register_to_get_started': 'خۆتی تۆمار بکە بۆ دەستپێکردن',
      'full_name': 'ناوی تێدا',
      'phone_number': 'ژمارەی تەلەفۆن',
      'confirm_password': 'شیفرە دووپات بکە',
      'i_am_a': 'من...',
      'employer': 'بەرپرس کار',
      'job_seeker': 'گەڕان بەدوای کار',
      'agree_terms': 'من وەرگری مەرج و شەرتەکان',
      'register': 'تۆمار',
      'already_have_account': 'بێدەنگ ئەکاونتی هەیت؟',
      'loading': 'بارکردن...',
      'find_perfect_job': 'وەرگری کاری خۆت بدۆ',
      'please_fill_all_fields': 'تکایە هەموو خانەکان پڕ بکە',
      'passwords_not_match': 'شیفرەکان یەک نین',
      'agree_to_terms': 'تکایە مەرج و شەرتەکان قبول بکە',
      'select_user_type': 'تکایە جۆری بەکاربێنەر دیاری بکە',
      'logged_in_successfully': 'بە سەرکەوتوویی چۆیتە ژوورەوە!',
      'login_failed': 'چوونە ژوورەوە شکست هێنا',
      'registration_failed': 'تۆمار شکست هێنا',
      'please_verify_email': 'تکایە ئیمەیلی خۆت تیپ بکەوە',
    },
    'tr': {
      'welcome_back': 'Hoş Geldin',
      'login_to_account': 'Hesabınıza giriş yapın',
      'email': 'E-posta',
      'enter_your_email': 'E-postanızı girin',
      'password': 'Şifre',
      'enter_your_password': 'Şifrenizi girin',
      'forgot_password': 'Şifreni mi unuttun?',
      'login': 'Giriş Yap',
      'dont_have_account': 'Hesabın yok mu?',
      'sign_up': 'Kaydol',
      'create_account': 'Hesap Oluştur',
      'register_to_get_started': 'Başlamak için kaydolun',
      'full_name': 'Ad Soyad',
      'phone_number': 'Telefon Numarası',
      'confirm_password': 'Şifreyi Onayla',
      'i_am_a': 'Ben...',
      'employer': 'İşveren',
      'job_seeker': 'İş Arıyorum',
      'agree_terms': 'Şartları ve koşulları kabul ediyorum',
      'register': 'Kaydol',
      'already_have_account': 'Zaten hesabın var mı?',
      'loading': 'Yükleniyor...',
      'find_perfect_job': 'Mükemmel İşini Bul',
      'please_fill_all_fields': 'Lütfen tüm alanları doldurun',
      'passwords_not_match': 'Şifreler eşleşmiyor',
      'agree_to_terms': 'Lütfen şartları ve koşulları kabul edin',
      'select_user_type': 'Lütfen kullanıcı türünü seçin',
      'logged_in_successfully': 'Başarıyla giriş yapıldı!',
      'login_failed': 'Giriş başarısız',
      'registration_failed': 'Kayıt başarısız',
      'please_verify_email': 'Lütfen e-postanızı doğrulayın',
    },
  };

  static String get(String key, String languageCode) {
    return _translations[languageCode]?[key] ?? _translations['en']![key]!;
  }

  static bool isRTL(String languageCode) {
    return languageCode == 'ar';
  }

  static TextDirection getTextDirection(String languageCode) {
    return isRTL(languageCode) ? TextDirection.rtl : TextDirection.ltr;
  }
}
